import { DailyPlan, DailyReport, Task, WeeklyReport, UserProfile } from '@/types';

function downloadBlob(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function csvEscape(value: string | number | undefined | null) {
  const s = String(value ?? '');
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function exportDailyReportCsv(
  plan: DailyPlan,
  tasks: Task[],
  user: UserProfile
) {
  const rows = [
    ['Field', 'Value'],
    ['User', user.fullName],
    ['Email', user.email],
    ['Date', plan.date],
    ['Goal', plan.goal],
    ['Completion %', plan.completionPercentage],
    ['Completed Tasks', plan.completedTasks],
    ['Pending Tasks', plan.pendingTasks],
    ['Streak', user.streak],
    ['XP', user.totalXP],
    [],
    ['Task Title', 'Session', 'Priority', 'Status', 'Completed At'],
    ...tasks.map((t) => [
      t.title,
      t.session,
      t.priority,
      t.status,
      t.completedAt || '',
    ]),
  ];

  const csv = rows.map((r) => r.map(csvEscape).join(',')).join('\n');
  downloadBlob(`pta-daily-report-${plan.date}.csv`, csv, 'text/csv;charset=utf-8');
}

export function exportWeeklyReportCsv(report: WeeklyReport, user: UserProfile) {
  const rows = [
    ['Field', 'Value'],
    ['User', user.fullName],
    ['Week Start', report.weekStart],
    ['Week End', report.weekEnd],
    ['Completed Tasks', report.completedTasks],
    ['Pending Tasks', report.pendingTasks],
    ['Completion %', report.completionPercentage],
    ['Consistency Score', report.consistencyScore],
    ['Goal Summary', report.weeklyGoalSummary],
    ['Achievements', report.achievements.join('; ')],
  ];
  const csv = rows.map((r) => r.map(csvEscape).join(',')).join('\n');
  downloadBlob(
    `pta-weekly-report-${report.weekStart}.csv`,
    csv,
    'text/csv;charset=utf-8'
  );
}

export function exportAnalyticsCsv(
  rows: { date: string; completion: number; tasksDone: number }[]
) {
  const header = ['Date', 'Completion %', 'Tasks Done'];
  const body = rows.map((r) => [r.date, r.completion, r.tasksDone]);
  const csv = [header, ...body].map((r) => r.map(csvEscape).join(',')).join('\n');
  downloadBlob('pta-analytics.csv', csv, 'text/csv;charset=utf-8');
}

/** Opens a print-ready HTML report (Save as PDF from the browser). */
export function exportReportPdf(opts: {
  title: string;
  subtitle?: string;
  stats: { label: string; value: string }[];
  sections?: { heading: string; lines: string[] }[];
}) {
  const statsHtml = opts.stats
    .map(
      (s) =>
        `<div style="flex:1;min-width:120px;padding:12px;border:1px solid #e2e8f0;border-radius:12px;margin:4px">
          <div style="font-size:11px;color:#64748b;text-transform:uppercase">${s.label}</div>
          <div style="font-size:22px;font-weight:800;margin-top:4px">${s.value}</div>
        </div>`
    )
    .join('');

  const sectionsHtml = (opts.sections || [])
    .map(
      (sec) =>
        `<h2 style="margin-top:24px;font-size:16px">${sec.heading}</h2>
         <ul>${sec.lines.map((l) => `<li style="margin:6px 0">${l}</li>`).join('')}</ul>`
    )
    .join('');

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><title>${opts.title}</title>
<style>
  body{font-family:Georgia,serif;color:#0f172a;padding:32px;max-width:800px;margin:0 auto}
  h1{font-size:28px;margin:0} .sub{color:#64748b;margin-top:6px}
  .stats{display:flex;flex-wrap:wrap;gap:8px;margin-top:24px}
  @media print{button{display:none}}
</style></head><body>
  <h1>${opts.title}</h1>
  ${opts.subtitle ? `<p class="sub">${opts.subtitle}</p>` : ''}
  <div class="stats">${statsHtml}</div>
  ${sectionsHtml}
  <p style="margin-top:40px;font-size:12px;color:#94a3b8">Generated by PTA Progress Tracker · ${new Date().toLocaleString()}</p>
  <script>window.onload=()=>setTimeout(()=>window.print(),200)</script>
</body></html>`;

  const w = window.open('', '_blank');
  if (!w) {
    downloadBlob(`${opts.title.replace(/\s+/g, '-').toLowerCase()}.html`, html, 'text/html');
    return;
  }
  w.document.write(html);
  w.document.close();
}

export function buildDailyPdfPayload(
  plan: DailyPlan,
  tasks: Task[],
  user: UserProfile,
  report?: DailyReport
) {
  return {
    title: `Daily Report — ${plan.date}`,
    subtitle: `${user.fullName} · ${plan.goal}`,
    stats: [
      { label: 'Completion', value: `${plan.completionPercentage}%` },
      { label: 'Done', value: String(plan.completedTasks) },
      { label: 'Pending', value: String(plan.pendingTasks) },
      { label: 'Streak', value: `${user.streak}d` },
    ],
    sections: [
      {
        heading: 'Tasks',
        lines: tasks.map((t) => `${t.status}: ${t.title} (${t.session})`),
      },
      {
        heading: 'Reflection',
        lines: [report?.reflection || 'No reflection recorded.', ...(report?.achievements || [])],
      },
    ],
  };
}
